<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ticketSupplierInfo [ <!ELEMENT ticketSupplierInfo (ticketSupplier)*>
<!ELEMENT ticketSupplier (name, event, address, telephone, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT event (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
]>

<ticketSupplierInfo>
  <ticketSupplier>
    <name>John Doe Inc.</name>
    <event>Concert</event>
    <address>15 Goldbrook Sq, Castleknock, Dublin 15</address>
    <telephone>+353 20 917 9714</telephone>
    <email>DJohnInc@gmail.com</email>
  </ticketSupplier>
  <ticketSupplier>
    <name>Jane Doe Inc.</name>
    <event>Football Match</event>
    <address>15 Goldbrook Sq, Castleknock, Dublin 15</address>
    <telephone>+353 20 914 2546</telephone>
    <email>DJaneInc@gmail.com</email>
  </ticketSupplier>
  <ticketSupplier>
    <name>Janet Doe Inc.</name>
    <event>Festival</event>
    <address>15 Goldbrook Sq, Castleknock, Dublin 15</address>
    <telephone>+353 20 913 4417</telephone>
    <email>DJanetInc@gmail.com</email>
  </ticketSupplier>
</ticketSupplierInfo>
